# Generated by Django 5.0.1 on 2024-02-03 20:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='intitule')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('En arrêt', 'En arrêt'), ('Effectué', 'Effectué')], default='En attente', max_length=20)),
                ('priorite', models.CharField(choices=[('Bas', 'Bas'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé')], max_length=20)),
                ('description', models.CharField(default='description', max_length=500)),
                ('n_OS', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'OS")),
                ('ok', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('duree_estimee', models.DurationField(default=datetime.timedelta(seconds=14400), verbose_name='Durée estimée')),
                ('duree_reelle', models.DurationField(blank=True, null=True, verbose_name='Durée réelle')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('activite', models.ManyToManyField(db_index=True, to='task.activite', verbose_name='Activite')),
                ('appelant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.appelant', verbose_name='Celui qui appelle')),
                ('categorie', models.ManyToManyField(db_index=True, to='task.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport_text', models.TextField(verbose_name='Rapport')),
                ('technicien_list', models.CharField(max_length=250, null=True, verbose_name='liste des technicien')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tache', verbose_name='Rapport de la tache :')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicienTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False, verbose_name='tache effectuer')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tache')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='techniciens')),
            ],
            options={
                'unique_together': {('technicien', 'tache')},
            },
        ),
        migrations.AddField(
            model_name='tache',
            name='assignations',
            field=models.ManyToManyField(through='task.TechnicienTache', to='ressource.technicien'),
        ),
    ]
