# Generated by Django 5.0.1 on 2024-02-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile', verbose_name='profile')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenom')),
                ('tel', models.CharField(max_length=20, verbose_name='telephone')),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='matricune')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('vitesse_execution', models.FloatField(default=0.0, verbose_name="Vitesse d'exécution")),
                ('efficacite', models.FloatField(default=0.0, verbose_name='Efficacité')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='echnicien')),
            ],
        ),
    ]
